// export const CLASSIFIER = 'classifier';
export const EXPLORER = 'EXPLORER';
export const DATASET = 'dataset';
export const LOGIN = 'login';
export const LOGOUT = 'logout';
// export const TSNE = 'tsne';
// export const NEIGHBOURS = 'neighbours';
// export const TRIPLETS = 'triplets';
// export const LABELS = 'labels';
